apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        imagePullPolicy: Never
        image: supergraph-demo-fed2-products:latest
        ports:
        - containerPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        imagePullPolicy: Never
        image: supergraph-demo-fed2-inventory:latest
        ports:
        - containerPort: 4000
---

apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    run: products
spec:
  # type: NodePort
  ports:
  - port: 8081
    targetPort: 4000
    protocol: TCP
    name: http
  # - port: 443
  #   protocol: TCP
  #   name: https
  selector:
    run: products